### ISSUE TITLE
BB_KEY and username exposed in code

### ISSUE THREAD

**Issue by ABeltramo** [ftramer/Steal-ML#6]
You should redact `BB_KEY` and `username` in `tree.py`.
https://github.com/ftramer/Steal-ML/blob/e37c67b2f74e42a85370ce431bc9d4e391b0ed8b/trees/bigml_wrapper/tree.py#L24

**Comment by ftramer** [comment]
Thanks! Yes this isn't ideal but the corresponding account actually no longer exists so this is just to illustrate how the code should be used with an open account.
