### ISSUE TITLE
No datasets

### ISSUE THREAD

**Issue by zedoul** [ftramer/Steal-ML#7]
In Steal-ML/trees/bigml_wrapper/experiments/models.py, it says:

    # Download datasets using:
    # curl "https://bigml.io/public/dataset/{DATA_ID}/download?$BIGML_AUTH" > ../data/bigml_datasets/{DATA_ID}.csv

It is not true; it will return with the 404 error, because bigml.io does not support "public/dataset" URI. The instruction might have worked five year ago, I assume.

**Comment by ftramer** [comment]
Yes, this code worked with the BigML API from ~5 years ago and has not been maintained since.
I have no doubt their service has changed drastically since then so the exact attack implemented here likely no longer works.
